# Generated by Django 3.0.4 on 2020-04-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='squadron',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
