# Generated by Django 3.0.4 on 2020-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_military_school',
            field=models.BooleanField(default=False),
        ),
    ]
