# Generated by Django 3.0.4 on 2020-05-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import question.definition


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.PositiveSmallIntegerField()),
                ('q_file', models.FileField(null=True, upload_to='Listening Question Audio File')),
                ('q_content', models.TextField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('issued_freq', models.PositiveIntegerField(default=0)),
                ('correct_freq', models.PositiveIntegerField(default=0)),
                ('faulty_reason', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(default=question.definition.State['Saved'])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
    ]
