# Generated by Django 3.0.7 on 2020-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_file',
            field=models.FileField(null=True, upload_to='listening_question_audio_file'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
